/*
category
tool
technology
other
*/

export default {
  'Try it Now': 'category',
  Blog: 'category',
  Showcase: 'category',
  'Work in Progress': 'category',
  Software: 'category',
  Hardware: 'category',
  JavaScript: 'technology',
  'G-code': '',
  HTML: 'technology',
  CSS: 'technology',
  'C++': 'technology',
  Rust: 'technology',
  Python: 'technology',
  Java: 'technology',
  Git: 'tool',
  'Android App': 'category',
  Arduino: 'tool',
  NodeJS: 'technology',
  Electronics: 'skill',
  Web: 'category',
  Hacking: 'category',
  '3D Printing': 'technology',
  MIDI: '',
  Soldering: 'skill',
  Demo: 'category',
  'Photo Editing': 'skill',
  Tensorflow: 'technology',
  Keras: 'technology',
  'Artificial Intelligence': 'technology',
  Mutliprocessing: 'technology',
  'Google Drive API': 'technology',
  'Google Calendar API': 'technology',
  Multithreading: 'technology',
  Watchdog: 'tool',
  '3D Design': 'skill',
  '3D Rendering': 'skill',
  'Physics Calculations': 'skill',
  'Data Analysis': 'skill',
  'Data Processing': 'skill',
  Hashing: 'technology',
  Explosives: '',
  Security: '',
  RegExp: 'technology',
  Drone: '',
  'Cellular Automaton': '',
  'Android Studio': 'tool',
  Scripting: 'skill',
  Powershell: 'tool',
  vJoySerialFeeder: 'tool',
  Learning: 'category',
  Finances: '',
  Markdown: 'technology',
  PrismJS: 'technology',
  Selenium: 'technology',
  Xvfb: 'tool',
  Modular: '',
  'UI Design': 'skill',
  'Web-push': 'technology',
  'Service Worker': 'technology',
  'Raspberry Pi': 'technology',
  Encryption: 'technology',
  Robotics: 'category',
  Linux: 'tool',
  Bash: 'tool',
  Outdated: 'category',
  'Discord Bot': '',
  'Wolfram|Alpha API': 'technology',
  RC: 'category',
  Philosophy: 'skill',
  SSH: 'tool',
  SFTP: 'tool',
  Notion: 'tool',
  Organization: 'skill',
  Productivity: 'skill',
  'Low-level': 'skill',
  NextJS: 'technology',
  'VS Code': 'tool',
  Vim: 'tool',
  CSV: 'technology',
  LaTeX: 'technology',
  JSON: 'technology',
  YAML: 'technology',
  'Fusion 360': 'tool',
  Cura: 'tool',
  Figma: 'tool',
  'Wolfram Alpha': 'tool',
  'Arduino IDE': 'tool',
  Assembly: 'technology',
  Betaflight: 'tool',
  'Key Bindings': 'skill',
  FPV: 'skill',
  Cryptography: '',
  Chemistry: '',
  'Chrome Extension': '',
  OpenAI: 'technology',
};
