export default {
  'Try it Now': 'b',
  'Blog': 'b',
  'Showcase': 'b',
  'Work in Progress': 'b',
  'Software': 'b',
  'Hardware': 'b',
  'JavaScript': 'i',
  'HTML': 'i',
  'CSS': 'i',
  'C++': 'i',
  'Python': 'i',
  'Java': 'i',
  'Git': 'i',
  'App': 'u',
  'Arduino': 'u',
  'NodeJS': 'u',
  'Electronics': 'u',
  'Web': 'u',
  'Hacking': 'u',
  '3D Printing': 'u',
  'Radio Controlled': 'u',
  'Tech': 'u',
}