export default {
    'Try it Now': 'Projects to Try',
    'Blog': 'Blog Posts',
    'Showcase': '',
    'Work in Progress': '',
    'Software': 'Software Projects',
    'Hardware': 'Hardware Projects',
    'JavaScript': 'JavaScript Projects',
    'HTML': 'HTML Projects',
    'CSS': 'CSS Projects',
    'C++': 'C++ Projects',
    'Python': 'Python Projects',
    'Java': 'Java Projects',
    'Git': 'Git Projects',
    'App': 'Mobile Apps',
    'Arduino': 'Arduino Projects',
    'NodeJS': 'NodeJS Projects',
    'Electronics': 'Electronics Projects',
    'Web': 'Web Projects',
    'Hacking': 'Hacking Projects',
    '3D Printing': '3D Printing Projects',
    'Radio Controlled': 'Radio Controlled Projects',
    'Tech': 'Tech Projects',
  }