export default {
  'Try it Now': 'b',
  Blog: 'b',
  Showcase: 'b',
  'Work in Progress': 'b',
  Software: 'b',
  Hardware: 'b',
  JavaScript: 'i',
  'G-code': 'i',
  HTML: 'i',
  CSS: 'i',
  'C++': 'i',
  Python: 'i',
  Java: 'i',
  Git: 'i',
  'Android App': 'u',
  Arduino: 'u',
  NodeJS: 'u',
  Electronics: 'u',
  Web: 'u',
  Hacking: 'u',
  '3D Printing': 'u',
  MIDI: 'i',
  Soldering: '',
  Demo: 'b',
  'Photo Editing': '',
  Tensorflow: 'u',
  Keras: 'u',
  'Artificial Intelligence': '',
  Mutliprocessing: 'u',
  'Google Drive API': 'u',
  'Google Calendar API': 'u',
  Multithreading: 'u',
  Watchdog: 'u',
  '3D Design': 'i',
  '3D Rendering': 'i',
  'Physics Calculations': '',
  'Data Analysis': 'i',
  'Data Processing': 'i',
  Hashing: 'u',
  Explosives: '',
  Security: '',
  RegExp: 'i',
  Drone: 'u',
  'Cellular Automaton': '',
  'Android Studio': 'u',
  Scripting: 'b',
  Powershell: '',
  vJoySerialFeeder: 'u',
  Learning: 'b',
  Finances: '',
  Markdown: 'i',
  PrismJS: 'u',
  Selenium: 'u',
  Xvfb: 'u',
  Modular: '',
  'UI Design': '',
  'Web-push': 'u',
  'Service Worker': '',
  'Raspberry Pi': 'u',
  Encryption: 'u',
  Robotics: 'u',
  Linux: 'u',
  Bash: 'u',
  Outdated: 'b',
  'Discord Bot': 'u',
  'Wolfram|Alpha API': 'u',
  RC: 'u',
  Philosophy: '',
};
